'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const guarded=['qr-concreto/index.html','slump/index.html','setor_botoes/index.html','dosagem-concreto/index.html','dosagem-concreto/manual.html','checklist-usina/index.html','mapa-concretagem/index.html','controle-estatistico/index.html','alertas.html','pcp/index.html'];
test('todas as rotas internas usam guard',()=>{for(const file of guarded){const html=read(file);assert.match(html,/auth\/guard\.js/,file);assert.match(html,/data-app-key=/,file)}});
test('hub possui chaves para todos os cards',()=>{const html=read('index.html');const cards=[...html.matchAll(/<a class="app-card"/g)].length;const keys=[...html.matchAll(/<a class="app-card" data-app-key=/g)].length;assert.equal(keys,cards)});
test('frontend não expõe service role nem password hash',()=>{for(const file of ['auth/config.js','auth/client.js','auth/guard.js','auth/login.js','auth/admin-users.js']){const source=read(file);assert.doesNotMatch(source,/service_role|SUPABASE_SERVICE_ROLE_KEY|password_hash/i,file)}});
test('migration habilita RLS e não armazena senha',()=>{const sql=read('supabase/migrations/202606290001_auth_hub.sql');assert.match(sql,/enable row level security/);assert.match(sql,/references auth\.users/);assert.doesNotMatch(sql,/password_hash/)});
test('seed exige ambiente e não contém senha fixa',()=>{const seed=read('scripts/seed-master.mjs');for(const key of ['MASTER_EMAIL','MASTER_NAME','MASTER_USERNAME','MASTER_TEMP_PASSWORD','SUPABASE_SERVICE_ROLE_KEY'])assert.match(seed,new RegExp(key));assert.doesNotMatch(seed,/password\s*:\s*['"][^'"]+['"]/)});
test('suspensão global é explícita e reversível',()=>{assert.match(read('auth/config.js'),/authEnabled:\s*false/);assert.match(read('auth/guard.js'),/auth-suspended/)});
